# Generated by Django 5.0.1 on 2024-01-06 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_url_id_alter_url_alias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='url',
            name='expires_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
