# Generated by Django 5.0 on 2024-01-11 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_user_created_at_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
