# Generated by Django 5.0 on 2024-01-11 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
    ]
