# Generated by Django 5.0 on 2024-01-11 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_user_name_alter_user_email_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
    ]
